config/routes.rb
Rails.application.routes.draw do

  resources :articles do
    resources :comments
  end

  resources :posts do
    resources :comments
  end

  resources :pages do
  end

  # get "/pages/:page" => "pages#show"

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 4 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	http_basic_authenticate_with name: "admin", password: "admin", except: [:index, 'pages']

	def index
	    @articles = Article.all
	end

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def show
		@article = Article.find(params[:id])
	end

	def index
		@articles = Article.all
	end

	def destroy
  		@article = Article.find(params[:id])
  		@article.destroy

  		redirect_to articles_path
	end

	def create
		# render plains: params[:article].inspect

		#@article = Article.new(params[:article])
		#@article = Article.new(params.require(:article).permit(:title, :text))
		@article = Article.new(article_params)

		if @article.save
			# redirect_to @article
			redirect_to articles_path
		else
			render 'new'
		end

		# redirect_to @article
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
    		redirect_to @article
  		else
    		render 'edit'
  		end
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "admin", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  def edit
    @article = Article.find(params[:article_id])
  end

  def update
    @article = Article.find(params[:article_id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
  def destroy
    	@article = Article.find(params[:article_id])
    	@comment = @article.comments.find(params[:id])
    	@comment.destroy
    	redirect_to article_path(@article)
  	end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/a_propos_helper.rb
module AProposHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label 'Titre' %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label 'Description' %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Modification Tâche</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1><%= link_to 'Liste des Tâches', controller: 'articles' %> | <%= link_to 'A propos', controller: 'pages' %></h1>

<table>
  <tr>
    <th>Titre</th>
    <th>Description</th>
    <th colspan="2"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><strong><%= article.title %></td></strong>
      <td><%= article.text %></td>
      <td><%= link_to 'Plus en détails', article_path(article) %></td>
      <td><%= link_to 'Modifier', edit_article_path(article) %></td>
      <td><%= link_to 'Supprimer', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure ?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Créer Tâche', new_article_path %>

app/views/articles/new.html.erb
<h1>Nouvelle Tâche</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h1>Tâche plus en détail</h1>

<p>
  <strong>Titre :</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description :</strong>
  <%= @article.text %>
</p>

<%= link_to 'Modifier', edit_article_path(@article) %> |
<%= link_to 'Retour', articles_path %>

<h2>Commentaire(s)</h2>
<%= render @article.comments %>

<h2>Ajouter un commentaire :</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<p>
  <strong>Motif :</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Raison :</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Edit', edit_article_comment_path(@article) %> |
  <%= link_to 'Supprimer Commentaire', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label 'Motif' %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label 'Raison' %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/comments/index.html.erb
<h1>Listing commentaires</h1>

<table>
  <tr>
    <th>Motif</th>
    <th>Raison</th>
    <th colspan="2"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><strong><%= article.commenter %></td></strong>
      <td><%= article.body %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PartielRuby</title>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="color:black; font-family:Avenir; font-size: 1.5em; background-color:#EBECEB;">
    <div id="main-container" class="container">
  <div class="row">
    <div class="col-xs-3">
    </div>
    <div class="col-xs-9">
      <%= yield %>
    </div>
  </div>
</div>
  </body>
</html>

app/views/pages/index.html.erb
<h1><%= link_to 'Liste des Tâches', controller: 'articles' %>
 | <%= link_to 'A propos', controller: 'pages' %></h1>

<p>

  Powder gummies topping gummies topping sweet lollipop sesame snaps chocolate cake. Bear claw gummi bears chupa chups topping I love lollipop jelly beans chocolate pudding. Bonbon I love carrot cake marshmallow chupa chups tart cake icing. Brownie I love jelly jujubes. Cookie lollipop chocolate jujubes. I love cookie apple pie I love sesame snaps chocolate. Halvah topping ice cream I love apple pie lollipop dessert. Lemon drops marzipan jujubes toffee dragée powder caramels caramels jelly-o. Chocolate lemon drops biscuit soufflé danish bear claw. Marzipan fruitcake I love. Candy dragée bear claw jelly-o gummi bears marzipan. Topping halvah halvah I love sesame snaps. Tiramisu candy canes sweet roll liquorice chocolate bar wafer.
Chocolate cake liquorice pie I love chocolate cake wafer I love. Chocolate cake toffee pudding dessert biscuit cotton candy lollipop. Marzipan gummies lemon drops jelly-o chupa chups muffin jelly candy canes. Sesame snaps caramels gummi bears pudding dessert. Dragée brownie apple pie danish danish I love caramels. Lollipop bear claw jelly lollipop jelly bonbon brownie brownie I love. Jujubes cake jelly-o caramels gingerbread. I love bear claw sweet roll fruitcake chocolate bar fruitcake. Jujubes marshmallow I love I love fruitcake pudding halvah sesame snaps halvah. Bonbon wafer apple pie gummies chocolate bar wafer. Pie lemon drops cupcake liquorice caramels cheesecake jujubes. Apple pie gummies sweet jelly-o topping.
Sweet roll topping jelly beans sweet pie I love muffin sesame snaps. Sugar plum tootsie roll icing apple pie tiramisu toffee. Biscuit chocolate caramels. Marzipan I love sesame snaps chupa chups chocolate bar chupa chups apple pie carrot cake. Cheesecake jelly beans macaroon I love carrot cake wafer sweet. Topping tart I love cookie I love. Jelly-o marshmallow icing. Jelly bonbon donut powder I love soufflé dessert oat cake jujubes. Croissant cheesecake icing croissant. Soufflé cookie gummi bears. Chocolate donut muffin cake cheesecake dragée bonbon. Jelly cookie pudding danish macaroon. Bonbon macaroon croissant chocolate lollipop cookie tart wafer.
I love carrot cake I love I love pudding lollipop tootsie roll. Powder macaroon sesame snaps jelly marzipan chocolate. Macaroon pastry caramels toffee liquorice I love. Macaroon chocolate bar biscuit tootsie roll caramels sweet roll toffee bear claw. Dessert jujubes I love liquorice lollipop I love. Dessert brownie sweet roll icing. I love I love candy canes jelly bonbon tart ice cream. Lollipop gingerbread I love. Candy canes I love chupa chups. Ice cream halvah topping cupcake I love carrot cake. Dessert apple pie dessert caramels muffin. I love fruitcake jelly beans. Biscuit marzipan sesame snaps chocolate cake. Caramels tart sweet cookie marshmallow.
Jelly-o jelly topping marzipan chocolate cake liquorice bear claw fruitcake. Dragée candy canes candy canes I love halvah wafer macaroon. I love candy chocolate macaroon chocolate cake soufflé cupcake marshmallow pie. Cotton candy gummi bears lemon drops lollipop. Wafer lemon drops cookie cake soufflé ice cream marzipan I love cotton candy. Sugar plum bonbon lollipop muffin liquorice jujubes chocolate cake. Apple pie dessert tootsie roll chocolate cake. Cookie jelly-o chocolate cake. Chocolate bar pie I love jujubes. I love lemon drops oat cake carrot cake I love powder topping cookie. Sweet roll bear claw cake lollipop. Sesame snaps tootsie roll pudding donut cupcake sugar plum caramels. Lollipop croissant biscuit bear claw cotton candy.
</p>

<%= link_to 'Retour', articles_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Liste des Tâches', controller: 'articles' %>
<%= link_to 'A propos', controller: 'pages' %>